#!/usr/bin/env python
#Retrieves IUS Package URL
import os, sys
from launchpadlib.launchpad import Launchpad

try:
    input = sys.argv[1]
except IndexError:
    sys.exit(1)

launchpad = Launchpad.login_anonymously(os.path.basename(sys.argv[0]), 'production')
ius = launchpad.projects.search(text='ius')[0]

# Package Search
package = launchpad.branches.getByUrl(url='lp:~ius-coredev/ius/' + input)

if package:
    print input + ':', package.web_link
else:
    print input, 'is not a IUS Package'
